# MkDocs Configuration for DocuSnap-Backend Architecture Analysis
site_name: DocuSnap-Backend Architecture Analysis
site_description: DocuSnap-Backend System Architecture Analysis Documentation
site_author: Ziming Zhou
site_url: ""

# Repository
repo_name: JI-DeepSleep/DocuSnap-Backend
repo_url: https://github.com/JI-DeepSleep/DocuSnap-Backend
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2025 Ziming Zhou

# Configuration
theme:
  name: material
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: JI-DeepSleep
      repo: DocuSnap-Backend
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extra
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

# Navigation Structure
nav:
  - Home: index.md
  - Project Overview:
    - Background: overview/background.md
    - Target Users: overview/target-users.md
    - Core Features: overview/core-features.md
  - Technology Stack:
    - Technology Selection: tech-stack/technology-selection.md
    - Selection Rationale: tech-stack/selection-rationale.md
  - Architecture Design:
    - Architecture Overview: architecture/overview.md
    - Architecture Diagrams: architecture/diagrams.md
    - Layer Description: architecture/layers.md
  - Core Modules:
    - Module Overview: core-modules/overview.md
    - Task Processing Module: core-modules/task-processing.md
    - OCR Processing Module: core-modules/ocr-processing.md
    - LLM Processing Module: core-modules/llm-processing.md
    - Security & Encryption Module: core-modules/security-encryption.md
    - Cache & Persistence Module: core-modules/cache-persistence.md
    - Module Relationships: core-modules/relationships.md
  - Typical Workflows:
    - Workflow Overview: workflows/overview.md
    - Document Processing Workflow: workflows/document-processing.md
    - Form Processing Workflow: workflows/form-processing.md
    - Form Auto-filling Workflow: workflows/form-filling.md
    - Data Flow Diagrams: workflows/data-flow.md
  - Code Quality:
    - Quality Assessment: code-quality/assessment.md
    - Design Patterns: code-quality/design-patterns.md
    - Improvement Suggestions: code-quality/improvement-suggestions.md
  - Deployment Architecture:
    - Deployment Overview: deployment/overview.md
    - Deployment Diagrams: deployment/diagrams.md
    - Technology Stack: deployment/tech-stack.md
    - Scalability & Fault Tolerance: deployment/scalability-fault-tolerance.md
  - Conclusions & Recommendations:
    - Quick Start Guide: conclusions/quick-start.md
    - Optimization Directions: conclusions/optimization.md
    - Summary Assessment: conclusions/summary.md
    - References: conclusions/references.md
